/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BApp: typeof import('bootstrap-vue-next/components/BApp')['BApp']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BButtonGroup: typeof import('bootstrap-vue-next/components/BButton')['BButtonGroup']
    BCollapse: typeof import('bootstrap-vue-next/components/BCollapse')['BCollapse']
    BFormTextarea: typeof import('bootstrap-vue-next/components/BFormTextarea')['BFormTextarea']
    BListGroup: typeof import('bootstrap-vue-next/components/BListGroup')['BListGroup']
    BListGroupItem: typeof import('bootstrap-vue-next/components/BListGroup')['BListGroupItem']
    BSpinner: typeof import('bootstrap-vue-next/components/BSpinner')['BSpinner']
    MusicPanel: typeof import('./components/MusicPanel.vue')['default']
    PromptPanel: typeof import('./components/PromptPanel.vue')['default']
  }
}
